//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SqLite.Data {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class dataSettings : global::System.Configuration.ApplicationSettingsBase {
        
        private static dataSettings defaultInstance = ((dataSettings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new dataSettings())));
        
        public static dataSettings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=SQLiteDatabase\\Products.sqlite; Version=3;")]
        public string SQLITE_URI {
            get {
                return ((string)(this["SQLITE_URI"]));
            }
            set {
                this["SQLITE_URI"] = value;
            }
        }
    }
}
